/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aim_CONSTANTS_H
#define aim_CONSTANTS_H

#include "aim_types.h"



class aimConstants {
 public:
  aimConstants();

};

extern const aimConstants g_aim_constants;



#endif
